/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package josephmoscoso_lab9;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joseph
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_usuarios = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jb_crearusuario = new javax.swing.JButton();
        jb_listarusuarios = new javax.swing.JButton();
        jd_crearuser = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jb_crear = new javax.swing.JButton();
        tf_nombre = new javax.swing.JTextField();
        js_edad = new javax.swing.JSpinner();
        tf_user = new javax.swing.JTextField();
        pf_pass = new javax.swing.JPasswordField();
        jd_listaruser = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_users = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jb_eliminaruser = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jd_album = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jb_crearalbum = new javax.swing.JButton();
        jb_listaralbum = new javax.swing.JButton();
        jd_calbum = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_nombrealbum = new javax.swing.JTextField();
        tf_nombreartista = new javax.swing.JTextField();
        jb_creara = new javax.swing.JButton();
        jd_listaralbum = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_albums = new javax.swing.JTable();
        jb_eliminaralbum = new javax.swing.JButton();
        jb_cancionesa = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        canciones = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_listacanciones = new javax.swing.JTable();
        jd_canciones = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_albumas = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jb_agregarcancion = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_nombres = new javax.swing.JTextField();
        js_duracion = new javax.swing.JSpinner();
        tf_genero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jb_usuarios = new javax.swing.JButton();
        jb_canciones = new javax.swing.JButton();
        jb_albums = new javax.swing.JButton();
        jb_login = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_cargar = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Usuarios");

        jb_crearusuario.setText("Crear Usuario");
        jb_crearusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearusuarioMouseClicked(evt);
            }
        });

        jb_listarusuarios.setText("Listar Usuarios");
        jb_listarusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listarusuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_usuariosLayout = new javax.swing.GroupLayout(jd_usuarios.getContentPane());
        jd_usuarios.getContentPane().setLayout(jd_usuariosLayout);
        jd_usuariosLayout.setHorizontalGroup(
            jd_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_usuariosLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jd_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_usuariosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_usuariosLayout.createSequentialGroup()
                        .addComponent(jb_crearusuario)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jd_usuariosLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jb_listarusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 108, Short.MAX_VALUE))
        );
        jd_usuariosLayout.setVerticalGroup(
            jd_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_usuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_crearusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_listarusuarios)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Creacion de usuario");

        jLabel4.setText("Nombre");

        jLabel5.setText("Edad");

        jLabel6.setText("Username");

        jLabel7.setText("Password");

        jb_crear.setText("Crear");
        jb_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMouseClicked(evt);
            }
        });

        js_edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        javax.swing.GroupLayout jd_crearuserLayout = new javax.swing.GroupLayout(jd_crearuser.getContentPane());
        jd_crearuser.getContentPane().setLayout(jd_crearuserLayout);
        jd_crearuserLayout.setHorizontalGroup(
            jd_crearuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearuserLayout.createSequentialGroup()
                .addGroup(jd_crearuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearuserLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3))
                    .addGroup(jd_crearuserLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jd_crearuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_crearuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_user)
                            .addComponent(pf_pass))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearuserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_crear)
                .addGap(167, 167, 167))
        );
        jd_crearuserLayout.setVerticalGroup(
            jd_crearuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearuserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_crearuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_crearuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_crearuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jb_crear)
                .addGap(19, 19, 19))
        );

        tb_users.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tb_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_users);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Usuarios");

        jb_eliminaruser.setText("Eliminar");
        jb_eliminaruser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminaruserMouseClicked(evt);
            }
        });

        jLabel9.setText("*Seleccione en la tabla y luego presione boton para eliminar");

        javax.swing.GroupLayout jd_listaruserLayout = new javax.swing.GroupLayout(jd_listaruser.getContentPane());
        jd_listaruser.getContentPane().setLayout(jd_listaruserLayout);
        jd_listaruserLayout.setHorizontalGroup(
            jd_listaruserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listaruserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_listaruserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listaruserLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listaruserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jd_listaruserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listaruserLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(239, 239, 239))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listaruserLayout.createSequentialGroup()
                                .addComponent(jb_eliminaruser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addContainerGap())))))
        );
        jd_listaruserLayout.setVerticalGroup(
            jd_listaruserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listaruserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_listaruserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_eliminaruser)
                    .addComponent(jLabel9))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Albums");

        jb_crearalbum.setText("Crear Album");
        jb_crearalbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearalbumMouseClicked(evt);
            }
        });

        jb_listaralbum.setText("Listar Album");
        jb_listaralbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listaralbumMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_albumLayout = new javax.swing.GroupLayout(jd_album.getContentPane());
        jd_album.getContentPane().setLayout(jd_albumLayout);
        jd_albumLayout.setHorizontalGroup(
            jd_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_albumLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jd_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_albumLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jd_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_albumLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_albumLayout.createSequentialGroup()
                                .addComponent(jb_crearalbum)
                                .addGap(17, 17, 17))))
                    .addComponent(jb_listaralbum, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jd_albumLayout.setVerticalGroup(
            jd_albumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_albumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_crearalbum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_listaralbum)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Crear Album");

        jLabel12.setText("Nombre del album");

        jLabel13.setText("Artista");

        jb_creara.setText("Crear album");
        jb_creara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_calbumLayout = new javax.swing.GroupLayout(jd_calbum.getContentPane());
        jd_calbum.getContentPane().setLayout(jd_calbumLayout);
        jd_calbumLayout.setHorizontalGroup(
            jd_calbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_calbumLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jd_calbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_calbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jd_calbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_nombrealbum)
                        .addComponent(tf_nombreartista, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_calbumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_creara)
                .addGap(159, 159, 159))
        );
        jd_calbumLayout.setVerticalGroup(
            jd_calbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_calbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jd_calbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_nombrealbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_calbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_nombreartista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_creara)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Albums Disponibles");

        tb_albums.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tb_albums.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tb_albums);

        jb_eliminaralbum.setText("Eliminar album");
        jb_eliminaralbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminaralbumMouseClicked(evt);
            }
        });

        jb_cancionesa.setText("Ver lista de canciones de un album");
        jb_cancionesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancionesaMouseClicked(evt);
            }
        });

        jLabel15.setText("*Seleccione en la tabla y luego presione el boton correspondiente");

        javax.swing.GroupLayout jd_listaralbumLayout = new javax.swing.GroupLayout(jd_listaralbum.getContentPane());
        jd_listaralbum.getContentPane().setLayout(jd_listaralbumLayout);
        jd_listaralbumLayout.setHorizontalGroup(
            jd_listaralbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listaralbumLayout.createSequentialGroup()
                .addGroup(jd_listaralbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listaralbumLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_listaralbumLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel14))
                    .addGroup(jd_listaralbumLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jd_listaralbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addGroup(jd_listaralbumLayout.createSequentialGroup()
                                .addComponent(jb_eliminaralbum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_cancionesa)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_listaralbumLayout.setVerticalGroup(
            jd_listaralbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listaralbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_listaralbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_eliminaralbum)
                    .addComponent(jb_cancionesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Lista de Canciones");

        table_listacanciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_listacanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(table_listacanciones);

        javax.swing.GroupLayout cancionesLayout = new javax.swing.GroupLayout(canciones.getContentPane());
        canciones.getContentPane().setLayout(cancionesLayout);
        cancionesLayout.setHorizontalGroup(
            cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancionesLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancionesLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancionesLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        cancionesLayout.setVerticalGroup(
            cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );

        tb_albumas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tb_albumas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tb_albumas);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Albums");

        jb_agregarcancion.setText("Agregar cancion");
        jb_agregarcancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarcancionMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Agregar canciones");

        jLabel18.setText("Nombre de la Cancion");

        jLabel20.setText("Duracion(Segundos)");

        jLabel21.setText("Genero");

        js_duracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 2000, 1));

        javax.swing.GroupLayout jd_cancionesLayout = new javax.swing.GroupLayout(jd_canciones.getContentPane());
        jd_canciones.getContentPane().setLayout(jd_cancionesLayout);
        jd_cancionesLayout.setHorizontalGroup(
            jd_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_cancionesLayout.createSequentialGroup()
                .addGroup(jd_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_cancionesLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel17))
                    .addGroup(jd_cancionesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jd_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_cancionesLayout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jb_agregarcancion))))
                    .addGroup(jd_cancionesLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jd_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombres, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(tf_genero)
                            .addComponent(js_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jd_cancionesLayout.setVerticalGroup(
            jd_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_cancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(10, 10, 10)
                .addGroup(jd_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(js_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_cancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_agregarcancion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Reproductor de musica");

        jb_usuarios.setText("Usuarios");
        jb_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_usuariosMouseClicked(evt);
            }
        });

        jb_canciones.setText("Canciones");
        jb_canciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancionesMouseClicked(evt);
            }
        });

        jb_albums.setText("Albums");
        jb_albums.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_albumsMouseClicked(evt);
            }
        });

        jb_login.setText("Log In");

        jb_guardar.setText("Guardar Usuarios");

        jb_cargar.setText("Cargar Usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jb_usuarios))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jb_cargar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jb_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(144, 144, 144))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jb_login)
                                .addComponent(jb_albums))
                            .addGap(155, 155, 155))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(128, 128, 128)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_usuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_canciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_albums)
                .addGap(11, 11, 11)
                .addComponent(jb_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_cargar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_usuariosMouseClicked
        // TODO add your handling code here:
        jd_usuarios.setModal(true);
        jd_usuarios.pack();
        jd_usuarios.setLocationRelativeTo(this);
        jd_usuarios.setVisible(true);
    }//GEN-LAST:event_jb_usuariosMouseClicked

    private void jb_crearusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearusuarioMouseClicked
        // TODO add your handling code here:
        jd_crearuser.setModal(true);
        jd_crearuser.pack();
        jd_crearuser.setLocationRelativeTo(this);
        jd_crearuser.setVisible(true);
    }//GEN-LAST:event_jb_crearusuarioMouseClicked

    private void jb_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMouseClicked
        // TODO add your handling code here:
        try {
            user.add(new usuarios(tf_nombre.getText(), (Integer) js_edad.getValue(), tf_user.getText(), pf_pass.getText()));
            tf_nombre.setText("");
            tf_user.setText("");
            pf_pass.setText("");
            JOptionPane.showMessageDialog(jd_crearuser, "Usuario registrado con exito");
            jd_crearuser.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_crearuser, "Error, dato incorrecto\nvuelva a intentarlo");
        }
    }//GEN-LAST:event_jb_crearMouseClicked

    private void jb_listarusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listarusuariosMouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel m = new DefaultTableModel();
            m.addColumn("Nombre");
            m.addColumn("Edad");
            m.addColumn("Username");
            m.addColumn("Contraseña");
            tb_users.setModel(m);
            String[] col = new String[4];
            for (int i = 0; i < user.size(); i++) {
                col[0] = user.get(i).getNombre();
                col[1] = Integer.toString(user.get(i).getEdad());
                col[2] = user.get(i).getUser();
                col[3] = user.get(i).getContra();
                m.addRow(col);
            }
            tb_users.setModel(m);
            jd_listaruser.setModal(true);
            jd_listaruser.pack();
            jd_listaruser.setLocationRelativeTo(this);
            jd_listaruser.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_listarusuariosMouseClicked
    public void actualizarusers() {
        try {
            DefaultTableModel m = new DefaultTableModel();
            m.addColumn("Nombre");
            m.addColumn("Edad");
            m.addColumn("Username");
            m.addColumn("Contraseña");
            tb_users.setModel(m);
            String[] col = new String[4];
            for (int i = 0; i < user.size(); i++) {
                col[0] = user.get(i).getNombre();
                col[1] = Integer.toString(user.get(i).getEdad());
                col[2] = user.get(i).getUser();
                col[3] = user.get(i).getContra();
                m.addRow(col);
            }
            tb_users.setModel(m);
        } catch (Exception e) {
        }
    }
    private void jb_eliminaruserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminaruserMouseClicked
        // TODO add your handling code here:
        try {
            if (tb_users.getSelectedRow() >= 0) {
                for (int i = 0; i < user.size(); i++) {
                    if (tb_users.getValueAt(tb_users.getSelectedRow(), 2).equals(user.get(i).getUser())) {
                        user.remove(i);
                        actualizarusers();
                    }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_eliminaruserMouseClicked

    private void jb_cancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancionesMouseClicked
        // TODO add your handling code here:
        actualizaralbumagregar();
        jd_canciones.setModal(true);
        jd_canciones.pack();
        jd_canciones.setLocationRelativeTo(this);
        jd_canciones.setVisible(true);
    }//GEN-LAST:event_jb_cancionesMouseClicked

    private void jb_albumsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_albumsMouseClicked
        // TODO add your handling code here:
        jd_album.setModal(true);
        jd_album.pack();
        jd_album.setLocationRelativeTo(this);
        jd_album.setVisible(true);
    }//GEN-LAST:event_jb_albumsMouseClicked

    private void jb_crearalbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearalbumMouseClicked
        // TODO add your handling code here:
        jd_calbum.setModal(true);
        jd_calbum.pack();
        jd_calbum.setLocationRelativeTo(this);
        jd_calbum.setVisible(true);
    }//GEN-LAST:event_jb_crearalbumMouseClicked

    private void jb_listaralbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listaralbumMouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel m = new DefaultTableModel();
            m.addColumn("Nombre del Album");
            m.addColumn("Nombre del Artista");
            tb_albums.setModel(m);
            String[] col = new String[2];
            for (int i = 0; i < al.size(); i++) {
                col[0] = al.get(i).getNombre();
                col[1] = al.get(i).getArtista();
                m.addRow(col);
            }
            tb_albums.setModel(m);
            jd_listaralbum.setModal(true);
            jd_listaralbum.pack();
            jd_listaralbum.setLocationRelativeTo(this);
            jd_listaralbum.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_listaralbumMouseClicked

    private void jb_crearaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearaMouseClicked
        // TODO add your handling code here:
        try {
            al.add(new albums(tf_nombrealbum.getText(), tf_nombreartista.getText()));
            tf_nombrealbum.setText("");
            tf_nombreartista.setText("");
            JOptionPane.showMessageDialog(jd_calbum, "Album creado con exito");
            jd_calbum.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_calbum, "Error, dato incorrecto\nvuelva a intentarlo");
        }
    }//GEN-LAST:event_jb_crearaMouseClicked

    private void jb_eliminaralbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminaralbumMouseClicked
        // TODO add your handling code here:
        try {
            if (tb_albums.getSelectedRow() >= 0) {
                for (int i = 0; i < al.size(); i++) {
                    if (tb_albums.getValueAt(tb_albums.getSelectedRow(), 0).equals(al.get(i).getNombre())) {
                        al.remove(i);
                        actualizaralbums();
                    }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_eliminaralbumMouseClicked

    private void jb_cancionesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancionesaMouseClicked
        // TODO add your handling code here:
        try {
            if (tb_albums.getSelectedRow() >= 0) {
                actualizarcanciones();
                canciones.setModal(true);
                canciones.pack();
                canciones.setLocationRelativeTo(this);
                canciones.setVisible(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_cancionesaMouseClicked
    public void actualizarcanciones() {
        try {
            DefaultTableModel m = new DefaultTableModel();
            m.addColumn("Nombre de la Cancion");
            m.addColumn("Artista");
            m.addColumn("Duracion(Segundos)");
            m.addColumn("Genero");
            table_listacanciones.setModel(m);
            String[] col = new String[4];
            for (int i = 0; i < al.size(); i++) {
                if (tb_albums.getValueAt(tb_albums.getSelectedRow(), 1).equals(al.get(i).getNombre())) {
                    for (int j = 0; j < al.get(i).getSongs().size(); j++) {
                        col[0] = al.get(i).getSongs().get(j).getNombre();
                        col[1] = al.get(i).getSongs().get(j).getArtista();
                        col[2] = Integer.toString(al.get(i).getSongs().get(j).getDuracion());
                        col[3] = al.get(i).getSongs().get(j).getGenero();
                        m.addRow(col);
                    }
                }
            }
            table_listacanciones.setModel(m);
        } catch (Exception e) {
        }
    }
    private void jb_agregarcancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarcancionMouseClicked
        // TODO add your handling code here:
        try {
            for (int i = 0; i < al.size(); i++) {
                if (tb_albumas.getValueAt(tb_albumas.getSelectedRow(), 0).equals(al.get(i).getNombre())) {
                    al.get(i).getSongs().add(new canciones(tf_nombres.getText(), (String) tb_albumas.getValueAt(tb_albumas.getSelectedRow(), 1), (Integer) js_duracion.getValue(), tf_genero.getText()));
                }
            }
            JOptionPane.showMessageDialog(jd_canciones, "Cancion agregada con exito");
            tf_nombres.setText("");
            tf_genero.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_agregarcancionMouseClicked
    public void actualizaralbumagregar() {
        try {
            DefaultTableModel m = new DefaultTableModel();
            m.addColumn("Nombre del Album");
            m.addColumn("Nombre del Artista");
            tb_albumas.setModel(m);
            String[] col = new String[2];
            for (int i = 0; i < al.size(); i++) {
                col[0] = al.get(i).getNombre();
                col[1] = al.get(i).getArtista();
                m.addRow(col);
            }
            tb_albumas.setModel(m);
        } catch (Exception e) {
        }
    }

    public void actualizaralbums() {
        try {
            DefaultTableModel m = new DefaultTableModel();
            m.addColumn("Nombre del Album");
            m.addColumn("Nombre del Artista");
            tb_albums.setModel(m);
            String[] col = new String[2];
            for (int i = 0; i < al.size(); i++) {
                col[0] = al.get(i).getNombre();
                col[1] = al.get(i).getArtista();
                m.addRow(col);
            }
            tb_albums.setModel(m);
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog canciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jb_agregarcancion;
    private javax.swing.JButton jb_albums;
    private javax.swing.JButton jb_canciones;
    private javax.swing.JButton jb_cancionesa;
    private javax.swing.JButton jb_cargar;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_creara;
    private javax.swing.JButton jb_crearalbum;
    private javax.swing.JButton jb_crearusuario;
    private javax.swing.JButton jb_eliminaralbum;
    private javax.swing.JButton jb_eliminaruser;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_listaralbum;
    private javax.swing.JButton jb_listarusuarios;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_usuarios;
    private javax.swing.JDialog jd_album;
    private javax.swing.JDialog jd_calbum;
    private javax.swing.JDialog jd_canciones;
    private javax.swing.JDialog jd_crearuser;
    private javax.swing.JDialog jd_listaralbum;
    private javax.swing.JDialog jd_listaruser;
    private javax.swing.JDialog jd_usuarios;
    private javax.swing.JSpinner js_duracion;
    private javax.swing.JSpinner js_edad;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JTable table_listacanciones;
    private javax.swing.JTable tb_albumas;
    private javax.swing.JTable tb_albums;
    private javax.swing.JTable tb_users;
    private javax.swing.JTextField tf_genero;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombrealbum;
    private javax.swing.JTextField tf_nombreartista;
    private javax.swing.JTextField tf_nombres;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
    ArrayList<usuarios> user = new ArrayList();
    ArrayList<albums> al = new ArrayList();
}
